-- DI favorites table (optional but recommended)
-- Used by DIView.vue for persistent favorite state.

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  task_type text not null default 'DI',
  question_id text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists favorites_user_task_question_uidx
  on public.favorites (user_id, task_type, question_id);

alter table public.favorites enable row level security;

drop policy if exists "favorites_select_own" on public.favorites;
drop policy if exists "favorites_insert_own" on public.favorites;
drop policy if exists "favorites_delete_own" on public.favorites;

create policy "favorites_select_own"
on public.favorites
for select
to authenticated
using (auth.uid() = user_id);

create policy "favorites_insert_own"
on public.favorites
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "favorites_delete_own"
on public.favorites
for delete
to authenticated
using (auth.uid() = user_id);
